// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO1QX7iEefRPNHGklsC_8P6flAtUl4YkQ',
    appId: '1:795822588703:web:a29d4dfa040ef3ead3e62a',
    messagingSenderId: '795822588703',
    projectId: 'flutter-crashlytics-ff39c',
    authDomain: 'flutter-crashlytics-ff39c.firebaseapp.com',
    storageBucket: 'flutter-crashlytics-ff39c.firebasestorage.app',
    measurementId: 'G-2N1D8ZGFE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAe4TGWoxtpCAFV2az6ZW7KjsRWjKYZZw',
    appId: '1:795822588703:android:2f6781aaea56f5b4d3e62a',
    messagingSenderId: '795822588703',
    projectId: 'flutter-crashlytics-ff39c',
    storageBucket: 'flutter-crashlytics-ff39c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKUoDniF49xvoqT0EqWf79gX50UeL99X4',
    appId: '1:795822588703:ios:9be6fc0185850716d3e62a',
    messagingSenderId: '795822588703',
    projectId: 'flutter-crashlytics-ff39c',
    storageBucket: 'flutter-crashlytics-ff39c.firebasestorage.app',
    iosBundleId: 'com.example.animationTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKUoDniF49xvoqT0EqWf79gX50UeL99X4',
    appId: '1:795822588703:ios:9be6fc0185850716d3e62a',
    messagingSenderId: '795822588703',
    projectId: 'flutter-crashlytics-ff39c',
    storageBucket: 'flutter-crashlytics-ff39c.firebasestorage.app',
    iosBundleId: 'com.example.animationTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO1QX7iEefRPNHGklsC_8P6flAtUl4YkQ',
    appId: '1:795822588703:web:900ec88747684b65d3e62a',
    messagingSenderId: '795822588703',
    projectId: 'flutter-crashlytics-ff39c',
    authDomain: 'flutter-crashlytics-ff39c.firebaseapp.com',
    storageBucket: 'flutter-crashlytics-ff39c.firebasestorage.app',
    measurementId: 'G-WQ66NWX0D7',
  );

}